"""Convert the transparent boot asset to frozen RGBA bytes (requires Pillow)."""
from pathlib import Path
from PIL import Image

ROOT = Path(__file__).resolve().parents[1]
source = Image.open(ROOT / "assets/branding/xbt-smooth.png").convert("RGBA")
parts = ['"""Generated by scripts/compile_boot_logo.py; preserve alpha."""\n']
for size in (80, 112):
    data = source.resize((size, size), Image.Resampling.LANCZOS).tobytes()
    parts.append("RGBA_%d = (\n" % size)
    parts.extend("    %r\n" % data[i:i+128] for i in range(0, len(data), 128))
    parts.append(")\n")
(ROOT / "src/krux/boot_logo_data.py").write_text("".join(parts), encoding="utf-8")
